MyKittyLocation/Models/CatModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;

namespace MyKittyLocation.Models
{
    [Table("Cats")]
    public class CatModel
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int? CatId { get; set; }
        [DisplayName("Numer obroży")]
        [Required(ErrorMessage = "Pole wymagane")]
        [MaxLength(10)]
        public string? CollarId { get; set; }
        [DisplayName("Imię")]
        [Required(ErrorMessage = "Pole wymagane")]
        [MaxLength(10)]
        public string? Name { get; set; }
        [DisplayName("Zdjęcie")]
        public byte[] Photo { get; set; }
        public string? OwnerID { get; set; }
        
    }
}

MyKittyLocation/Models/KittyLocationContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyKittyLocation.Models
{
    public class KittyLocationContext : DbContext
    {
        public KittyLocationContext(DbContextOptions options) : base(options)
        {
        }

        public DbSet<CatModel> Cats { get; set; }
    }
}

MyKittyLocation/Controllers/CatController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Security.Cryptography.X509Certificates;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyKittyLocation.Models;
using MyKittyLocation.Repositories;


namespace MyKittyLocation.Controllers
{
    public class CatController : Controller
    {
        private readonly ICatRepo _catRepo;

        public CatController(ICatRepo catRepo)
        {
            _catRepo = catRepo;
        }


        // GET: Cat
        
        public ActionResult Index()
        {  
            return View("Index", _catRepo.GetUserCats(User.FindFirst(ClaimTypes.Email).Value));
        }

        public ActionResult Logout()
        {
            Microsoft.AspNetCore.Authentication.AuthenticationHttpContextExtensions.SignOutAsync(HttpContext);
            return Index();
        }

        // GET: Cat/Details/5

        public ActionResult Details(int id)
        {

            return View(_catRepo.Get(id));
        }


        // GET: Cat/Create
        
        public ActionResult Create()
        {
            return View(new CatModel());
        }

        // POST: Cat/Create
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CatModel catModel)
        {
            if (HttpContext.Request.Form.Files.Any())
            {
                var photo = HttpContext.Request.Form.Files[0];

                MemoryStream ms = new MemoryStream();
                photo.CopyTo(ms);
                var photoArray = ms.ToArray();
                catModel.Photo = photoArray;
            }
            catModel.OwnerID = User.FindFirst(ClaimTypes.Email).Value;
            _catRepo.Add(catModel);
            return RedirectToAction(nameof(Index));
        }

        // GET: Cat/Edit/5
        
        public ActionResult Edit(int id)
        {
            return View(_catRepo.Get(id));
        }

        // POST: Cat/Edit/5
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, CatModel catModel)
        {
            var photo = HttpContext.Request.Form.Files[0];
            MemoryStream ms = new MemoryStream();
            photo.CopyTo(ms);
            var photoArray = ms.ToArray();
            catModel.Photo = photoArray;
            _catRepo.Update(id, catModel);

            return RedirectToAction(nameof(Index));
        }

        // GET: Cat/Delete/5
        public ActionResult Delete(int id)
        {
            return View(_catRepo.Get(id));
        }

        // POST: Cat/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, CatModel catModel)
        {
            _catRepo.Delete(id);

            return RedirectToAction(nameof(Index));

        }

       
    }
}

MyKittyLocation/Controllers/GoogleMapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MyKittyLocation.Controllers
{
    public class GoogleMapController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MyKittyLocation/Views/Cat/Create.cshtml
@using Microsoft.AspNetCore.Identity
@using Amazon.Extensions.CognitoAuthentication
@inject SignInManager<CognitoUser> SignInManager
@inject UserManager<CognitoUser> UserManager
@model MyKittyLocation.Models.CatModel

@{
    ViewData["Title"] = "Create";
}

<h1 class="display-4">Dodaj kotka</h1>

<h4>Uzupełnij dane i obserwuj gdzie biega Twoj kot!</h4>
<hr />
<div class="form">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CollarId"></label>
                <input asp-for="CollarId" class="form-control" />
                <span asp-validation-for="CollarId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input id="txtName" asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">

                <label asp-for="Photo" class="control-label"></label>
                <input asp-for="Photo" type="file" id="Photo" name="Photo" class="upload" onchange=DisplayFilesToUpload() multiple />
                <span asp-validation-for="Photo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a class="btn btn-dark" asp-action="Index">Powrót</a>
                <input type="submit" value="Dodaj" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>



<script>
    function DisplayFilesToUpload() {
        var element = document.getElementById("file");
        var html = "";

        html = "<h3>Image(s) to Upload</h3>"
        for (var i = 0; i < element.files.length; i++) {
            html += "<strong>" + (i + 1) + "</strong>. File: ";
            var file = element.files[i];
            if ('name' in file) { html += file.name + " ("; }
            if ('size' in file) { html += "size: " + file.size + " bytes)<br>"; }
        }

        html += "<div class='fileUpload btn btn-default'><span>Upload</span><input type='submit' class='upload' value='Upload'/></div>"
        document.getElementById("FilesToUpload").innerHTML = html;
    }
</script>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyKittyLocation/Views/Cat/Delete.cshtml
@using Microsoft.AspNetCore.Identity
@using Amazon.Extensions.CognitoAuthentication
@inject SignInManager<CognitoUser> SignInManager
@inject UserManager<CognitoUser> UserManager
@model MyKittyLocation.Models.CatModel

@{
    ViewData["Title"] = "Delete";
}

<h1 class="display-4">Usuń dane</h1>

<h3>Czy na pewno chcesz usunąć te dane?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-10">
            @Html.DisplayNameFor(model => model.CollarId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CollarId)
        </dd>
        <dt class="col-sm-10">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        @{
            string imageDataURL = "https://cdn1.iconfinder.com/data/icons/halloween-doodles-2/512/doodle_cat_cute_scary_kitten-512.png";
            if (Model.Photo != null)
            {
                var image = Model.Photo;
                string imageBase64Data = Convert.ToBase64String(image);
                imageDataURL = string.Format("data:image/jpg;base64,{0}", imageBase64Data);
            }

        }
        <dd class="col-sm-10">
            <img src="@imageDataURL" id="imgViever" width="200" height="200" style="border:1px solid #000000;" />
        </dd>

    </dl>

    <form asp-action="Delete">
        <a class="btn btn-dark" asp-action="Index">Powrót</a>
        <input type="submit" value="Usuń" class="btn btn-danger" />
    </form>
</div>

MyKittyLocation/Views/Cat/Details.cshtml
@using Microsoft.AspNetCore.Identity
@using Amazon.Extensions.CognitoAuthentication
@inject SignInManager<CognitoUser> SignInManager
@inject UserManager<CognitoUser> UserManager
@model MyKittyLocation.Models.CatModel

@{
    ViewData["Title"] = "Details";
}

<h1 class="display-4">@Html.DisplayFor(model => model.Name)</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-10">
            @Html.DisplayNameFor(model => model.CollarId)
        </dt>
        <dt></dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CollarId)
        </dd>

        @{
            string imageDataURL = "https://cdn1.iconfinder.com/data/icons/halloween-doodles-2/512/doodle_cat_cute_scary_kitten-512.png";
            if (Model.Photo != null)
            {
                var image = Model.Photo;
                string imageBase64Data = Convert.ToBase64String(image);
                imageDataURL = string.Format("data:image/jpg;base64,{0}", imageBase64Data);
            }

        }
        <dd class="col-sm-10">
            <img src="@imageDataURL" id="imgViever" width="200" height="200" style="border:1px solid #000000;" />
        </dd>
        <dt></dt>

        <a class="btn btn-success" asp-area="" asp-controller="GoogleMap" asp-action="Index">Zobacz gdzie biega @Html.DisplayFor(model => model.Name)!</a>

        <dt></dt>
    </dl>
</div>
<div>

    @Html.ActionLink("Edytuj", "Edit", new { id = Model.CatId }, new { @class = "btn btn-warning" })
    @Html.ActionLink("Usuń", "Delete", new { id = Model.CatId }, new { @class = "btn btn-danger" })

    <a class="btn btn-dark" asp-action="Index">Powrót</a>
</div>

MyKittyLocation/Views/Cat/Edit.cshtml
@using Microsoft.AspNetCore.Identity
@using Amazon.Extensions.CognitoAuthentication
@inject SignInManager<CognitoUser> SignInManager
@inject UserManager<CognitoUser> UserManager
@model MyKittyLocation.Models.CatModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Zmień dane kota</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CollarId" class="control-label"></label>
                <input asp-for="CollarId" class="form-control" />
                <span asp-validation-for="CollarId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Photo" class="control-label"></label>
                <input asp-for="Photo" type="file" id="Photo" name="selectFiles" class="upload" onchange=DisplayFilesToUpload() multiple />
                <span asp-validation-for="Photo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a class="btn btn-dark" asp-action="Index">Powrót</a>
                <input type="submit" value="Zapisz" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyKittyLocation/Views/Cat/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Security.Claims
@using Amazon.Extensions.CognitoAuthentication
@inject SignInManager<CognitoUser> SignInManager
@inject UserManager<CognitoUser> UserManager
@model IEnumerable<MyKittyLocation.Models.CatModel>

@{
    ViewData["Title"] = "Index";
}

<h1 class="display-4">Twoje Kotki</h1>

<p>
    <a class="btn btn-outline-info" asp-action="Create">Dodaj kotka i sprawdź gdzie spędza czas! </a>
</p>

@if (!Model.Any())
{
    <h4>Nie masz jeszcze dodanych kotów</h4>
}
else
{
    <table class="table table-responsive table-hover">

        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td style="width:65%">
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td style="width:35%">
                        @Html.ActionLink("Zobacz", "Details", new { id = item.CatId }, new { @class = "btn btn-info" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

MyKittyLocation/Views/GoogleMap/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using Amazon.Extensions.CognitoAuthentication
@inject SignInManager<CognitoUser> SignInManager
@inject UserManager<CognitoUser> UserManager
@model IEnumerable<MyKittyLocation.Models.CatModel>

@{
    ViewData["Title"] = "CatOnTheGoogleMap";
}

<title>@ViewBag.Title</title>

<h1 class="display-4">Tutaj jest!</h1>
<fieldset>
    <legend>Ale łobuz!</legend>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <div id="googleMap" style="height:500px;width:100%;"></div>
    <script>



        function getRndInteger(min, max) {
            return Math.floor(Math.random() * (max - min)) + min;
        }

        function myMap() {

            var minLat = 49298;
            var maxLat = 54861;
            var minLng = 23893;
            var maxLng = 14174;

            var lat = getRndInteger(minLat, maxLat) / 1000;
            var lng = getRndInteger(minLng, maxLng) / 1000;

            var myCenter = new google.maps.LatLng(lat, lng);
            var mapProp = { center: myCenter, zoom: 12, scrollwheel: false, draggable: true, mapTypeId: google.maps.MapTypeId.ROADMAP };
            var map = new google.maps.Map(document.getElementById("googleMap"), mapProp);
            var marker = new google.maps.Marker({ position: myCenter });
            marker.setMap(map);
        }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?AIzaSyDn1TAhuRtX0BZhMAKAjciObdPiqrwVsvg&callback=myMap"></script>
</fieldset>
<footer>
    <p>© @DateTime.Now.ToLocalTime()</p>
</footer> 

MyKittyLocation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyKittyLocation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-action="Index">MyKittyLocation</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">

                        </li>
                    </ul>
                </div>
                <partial name="_LoginPartial"  />
            </div>
        </nav>
        <partial name="_CookieConsentPartial" />
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Iwona Kapturkiewicz
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>